print("hello world")
print("develop s1")
print("develop s2")
print("develop s3")
print("feature2 s1")
print("feature2 s2")
print("feature2 s3")
print("develop s4")
print("Severe bug fixed for production hotfix: v0.1")
print("release s1")
print("release s2")
print("release s3.0")
print("release s4")